### ISSUE TITLE
[Question] How can we use netcoredbg for mono on x86

### ISSUE THREAD

**Issue by vikasgupta8** [Samsung/netcoredbg#115]
We are trying to use netcoredbg for dotnet with mono compiler. 

I have installed the netcoredbg from [here](https://github.com/Samsung/netcoredbg/releases/download/2.2.0-974/netcoredbg-linux-amd64.tar.gz) and tried to use it to debug a sample program build with dotnet with mono compiler.
Getting error "**A debug component is not installed**" as shown below.

```
root@vikas-x86:/home/ubuntu/netcoredbg# ./netcoredbg
ncdb> attach 2957868
 Error: 0x80131c3c: A debug component is not installed.
ncdb> q
^exit
root@vikas-x86:/home/ubuntu/netcoredbg#

```

Could you please help with it.

**Comment by gbalykov** [comment]
Do you mean that `2957868` process id is a managed application launched on top of mono runtime? Netcoredbg doesn't support debugging with mono runtime, only with coreclr.

**Comment by vikasgupta8** [comment]
Do you mean that 2957868 process id is a managed application launched on top of mono runtime?

> Yes, correct. `2957868 `is process id of sample C# program build and run with mono runtime compiler.

**Comment by viewizard** [comment]
Netcoredbg could use only CoreCLR debug API https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebug-interface, mono provide another debug API - http://docs.go-mono.com/index.aspx?link=xhtml%3Adeploy%2Fmono-api-debug.html.
We don't have planned to support mono debug API, since this will mean write another debugger.
