### ISSUE TITLE
CMake build incorrectly sets RID to `linux` on alpine

### ISSUE THREAD

**Issue by gfszr** [Samsung/netcoredbg#118]
When compiling `netcoredbg` on Alpine, the binary doesn't correctly running since the `libdbgshm.dll` is compiled with `glibc` and not `musl`. This stems from the fact that the RID used is `linux`, and not `linux-musl`, as can be seen here:
https://github.com/Samsung/netcoredbg/blob/db69338cf1606d8d327de0eaaf1694d8463af135/src/CMakeLists.txt#L222-L232

The expected behavior is that either `linux` or `linux-musl` chosen whether the host requires musl (alpine) or not.

**Comment by viewizard** [comment]
Note, `libdbgshm.so` is part of `Microsoft.Diagnostics.DbgShim` package (netcoredbg don't compile it during build), that `dotnet build` download during managed part build
https://github.com/Samsung/netcoredbg/blob/db69338cf1606d8d327de0eaaf1694d8463af135/src/managed/ManagedPart.csproj#L41
As I see, MS provide musl versions of `Microsoft.Diagnostics.DbgShim`, for example, https://www.nuget.org/packages/Microsoft.Diagnostics.DbgShim.linux-musl-x64, looks like `ManagedPart.csproj` should be corrected in order to download proper file.

**Comment by viewizard** [comment]
Btw, as I see you figure out this, did you check with RID_NAME `linux-musl`? Is it works for you (is it download proper package)?

**Comment by gfszr** [comment]
Yes, verified that overriding it with `linux-musl` does the job and it works 👍

**Comment by viewizard** [comment]
This is good news, thanks! :-)
This mean only `netcoredbg/src/CMakeLists.txt` correction is need.

I did try now find some libc (glibc/musl) detect for cmake in internet and looks like this is not so trivial.
You probably already have some proper/guaranty way to detect `musl` libc build in cmake? Could you please share it?
Or should we check some env and switch to `musl` build for Alpine?

**Comment by gfszr** [comment]
I don't have a 100% guarantee for musl, checking `/etc/alpine-release` does however detect that we're on alpine, which probably suffices - if that doesn't work out, manually speficying RID in an env var for managed part should be OK too (the rest are decided by the `CC` and `CXX` defined).

**Comment by viewizard** [comment]
@gfszr I am sure we could add `/etc/alpine-releas` file detection in cmake for sure and check that `RID_NAME` is defined by user or not, good point.

@gbalykov please take a look, we probably could add this changes for next sync.

**Comment by gfszr** [comment]
@viewizard wanted to let you know I've discovered another issue with alpine, but I don't think it's netcoredbg's fault: `libdbgshim.so` is compiled with a very small default stack size on `musl`, and this causes the thread that runs the `RuntimeStartup` hook (which eventually calls `Init()`) to get a segfault on stack access, which fails when actually trying to run a launched debuggee. 

It might be good to increase stack size for `netcoredbg` anyway when targeting `musl` which has small stacks generally, but it still doesn't solve that Microsoft's `libdbgshim.so` is compiled with a very small default stack size when targeting alpine - will probably post an issue on https://github.com/dotnet/diagnostics

**Comment by viewizard** [comment]
As I know, we don't use `stack_size` in cmake, I believe, you could just export `CMAKE_EXE_LINKER_FLAGS_INIT` or `LDFLAGS` (or something like that) before cmake usage in case of netcoredbg build with linker flags you need.

I really doubt we will add `stack_size`, since this looks like particular distro environment related, that each distro should care about itself... and in case this distro toolchain tell us in `LDFLAGS` - "build with N stack limit", not sure we should override it in cmake. I believe, package maintainer should care about this (at least it know what flags it could override in `LDFLAGS`).

**Comment by gbalykov** [comment]
This should be fixed in latest release. Feel free to reopen if you see any more related issues.
