### ISSUE TITLE
Stack frame ID is too large

### ISSUE THREAD

**Issue by lextm** [Samsung/netcoredbg#19]
vsdbg only generates 32 bit integer for stack frame ID, and libraries such as https://www.nuget.org/packages/Microsoft.VisualStudio.Shared.VsCodeDebugProtocol/ uses int (not long) throughout the code base.

However, this project seems to generate 64 bit integer, which can easily break interoperation with other libraries.

Is it possible to change the behavior to match vsdbg?

**Comment by lextm** [comment]
Related to #11 .

**Comment by lextm** [comment]
Did an experiment to change the IDs from int64 to int32, and it does work with Microsoft's debugger protocol adapter.

**Comment by ayuckhulk** [comment]
Thinking about this a little more, I suppose it's better to re-engineer some of netcoredbg internals and just use 32bit integers, because of https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin
There is actually a possible bug in current implementation of frameid because safe integer is 2^53.
So least we should move level part into higher bits instead of thread id (`(level << 32) | threadId)`.

**Comment by viewizard** [comment]
Fixed in https://github.com/Samsung/netcoredbg/commit/4fbdcdaed2179762f8e97f7ed8567d819be688a4
