### ISSUE TITLE
No Breakpoints Hit on Simple .NET Core Apps

### ISSUE THREAD

**Issue by brikabrak** [Samsung/netcoredbg#45]
**Environment:**
Windows 10.0.19041
VSCodium 1.50
dotnet 3.1.402
netcoredbg latest win64 binary [based on auto-release commit](https://github.com/Samsung/netcoredbg/commit/0c8a23f33fa039395570996d26b3ad2ae3dac84b)

**Related Issues:**
VSCodium/vscodium#82

**Issue:**
Attempting to debug a simple .NET Core console application leads to no breakpoints hit. Have reviewed the issue noted above and made changes to use debugger through `pipeTransport`. Only in the event of setting the `stopOnEntry` flag do I get a response from the debugger. Also does not work with `netcore 2.2`.

Using the following `launch.json`:
```json
{
    "name": ".NET Core Launch (console)",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/sometest.dll",
    "args": [],
    "cwd": "${workspaceFolder}",
    "console": "internalConsole",
    "stopAtEntry": false,
    "logging": {
        "engineLogging": true
    },
    "pipeTransport": {
        "pipeCwd": "${workspaceFolder}",
        "pipeProgram": "cmd",
        "pipeArgs": ["/c"],
        "debuggerPath": "C:/bin/netcoredbg/netcoredbg.exe --engineLogging=C:\\Temp\\a"
    }
}
```
[Logs](https://pastebin.pl/view/43810c6e)

On latest Mac OS version, the above works without issue.

Any help would be appreciated as I am not looking to go back to regular vscode or Visual Studio.

**Comment by viewizard** [comment]
I checked Windows binary from auto release. Just tested this binary with current tests from test suite, a lot of tests failed. Looks like we have some CI issue, since this old binary (tests failed due to unsupported features, that we already added into upstream). So, this is definitely old binary. Have no idea what is wrong with CI and why old binary was copied into release instead of create new one, need investigate this first.

@brikabrak any chance you could build debugger from sources?
Or you could test this one, that I built from current upstream just now for testing on Windows: 
[netcoredbg.zip](https://github.com/Samsung/netcoredbg/files/5373411/netcoredbg.zip)

**Comment by brikabrak** [comment]
@viewizard My frustration got the better of me when trying to get cmake to work that I abandoned building from source. Apparently I should have stuck with it because the build you posted worked on first go, hitting breakpoints as expected. Thanks so much! I hope you guys are able to get your CI issues fixed!

**Comment by gbalykov** [comment]
Closing since this seems to be fixed. Feel free to reopen if you have any more questions.
